name: Publish Python distributions to PyPI and TestPyPI
on:
  push:
    branches: [ main ]


jobs:
  build-n-publish:
    name: Change-version-number-and-commit
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@master
      with: 
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

        
    - name: execute py script # run the run.py to get the latest data
      if: startsWith(github.ref, 'refs/tags') != true
      run: |
         output=$(python ChangeVersionNumber.py)
         echo version=$output >> $GITHUB_ENV
         echo $output

    - name: commit-n-tag 
      if: startsWith(github.ref, 'refs/tags') == false
      uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.DURIN_PAT }} 
          custom_tag:  ${{ env.version }}

    


    - name: push files
      if: startsWith(github.ref, 'refs/tags') == false
      uses: ad-m/github-push-action@master
      with:
        tags: true
        github_token: ${{ secrets.DURIN_PAT }}


    - name: Install pypa/build
      if: startsWith(github.ref, 'refs/tags')
      run: python -m pip install build --user


    - name: Build a binary wheel and a source tarball
      if: startsWith(github.ref, 'refs/tags')
      run: python -m build --sdist --wheel --outdir dist/ .

    # Only publish to pypi if the commit has a tag. 

    - name: Publish distribution 📦 to Test PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

      

