name: Publish Python distributions to PyPI and TestPyPI

on:
  push:
    branches: [ main ]





jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: execute py script # run the run.py to get the latest data
      run: |
        python ChangeVersionNumber.py
        
        



    - name: commit file
      run: |
        git config --local user.email "ncsdurin@kth.se"
        git config --local user.name "ncsdurin"
        git add setup.py
        git commit -m "incremented version number -- with love from a robot"
        git push origin main

    #get change the version number and commit. Dont do it if there is a tag. 
    #- name: Commit with tag
      #uses:
      #with:

    - name: Install pypa/build
      run: python -m pip install build --user


    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/ .

    # Only publish to pypi if the commit has a tag. 


    - name: Publish distribution 📦 to Test PyPI
      if: github.event_name != 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
