name: TestScript

on:
  push:

jobs:
  name: lol
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@master

  - name: commit-n-tag 
      if: startsWith(github.ref, 'refs/tags/v') != true 
      run: |
        echo '${{ env.version }}'
        git config --local user.email "ncsdurin@kth.se"
        git config --local user.name "ncsdurin"
        git add .
        git commit -m "incremented version number -- with love from a robot"
        git tag ${{ env.version }}
    
  - name: push files
      if: startsWith(github.ref, 'refs/tags/v') != true 
      uses: ad-m/github-push-action@master
      with:
        tags: true
        github_token: ${{ secrets.DURIN_PAT }}

- name: Publish distribution 📦 to Test PyPI
    if: startsWith(github.ref, 'refs/tags')
    run: echo 'Hello there'